###
POST http://localhost:3000/new-user HTTP/1.1
content-type: application/json

{
    "registered_by_user_id": 1,
    "email": "jesusarellano334@gmail.com",
    "first_name": "Jespus",
    "identification_img_url": "google.com",
    "identification_img_file_name": "google.com",
    "last_name": "area",
    "mobile_number": "4521590132",
    "badge": "Bach",
    "adminuser": "AdminUser",
    "adminpassword": "Bach",
    "adminsub": "Bach",
    "arrivaldate": "Bach",
    "accessdate": "Bach",
    "limitdate": "Bach",
    "user_role": {
        "role": "role"
    },
    "organization_role": {  
        "region": "Bach",
        "zona": "Bach",
        "distrito": "Bach",
        "tienda": "Bach",
        "area": "Bach",
        "role": "Bach"
    }
}

###
GET http://localhost:3000/user/ID_STUFF

###
GET http://localhost:3000/users

###
POST http://localhost:3000/tag_id-user HTTP/1.1
Content-Type: application/json

{
    "tag_id": "3946b549",
    "id": "ID_STUFF"
}

###
POST http://localhost:3000/new-entrance HTTP/1.1
Content-Type: application/json

{
    "tag_id": "DHle7G{dh&72h^Jyu(j~^2vivK",
    "id_lectora": "inpulse/dt/pulses/Pulso404/tag-id",
    "event_type": "entrada"
}

###
GET http://localhost:3000/questionnaries HTTP/1.1

###
GET http://localhost:3000/questionnaries?track=TRACK_STUFF HTTP/1.1

###
POST http://localhost:3000/questionnarie HTTP/1.1
Content-Type: application/json

{
    "track": 1,
    "preguntas": [
        {
            "pregunta": "La función trim() modifica el objeto sobre el cual se invoca.",
            "respuesta_correcta": false
        },
        {
            "pregunta": "La función trim() modifica el objeto sobre el cual se invoca.",
            "respuesta_correcta": false
        },
        {
            "pregunta": "Node JS es un buen lenguaje.",
            "respuesta_correcta": true
        },
        {
            "pregunta": "Node JS es un buen lenguaje.",
            "respuesta_correcta": true
        }
    ]
}

###
POST http://localhost:3000/admonitions HTTP/1.1
Content-Type: application/json

[
    {
        "tag_id": "alejandr",
        "points": {{$randomInt 5 50}},
        "id_lectora": "31234"
    },    {
        "tag_id": "alejandre",
        "points": {{$randomInt 5 50}},
        "id_lectora": "1244"
    },    {
        "tag_id": "alejandr1",
        "points": {{$randomInt 5 50}},
        "id_lectora": "3123421"
    }
]

###
POST http://localhost:3000/answers HTTP/1.1
Content-Type: application/json

[{
    "track": 4,
    "tag_id": "alejandr1",
    "preguntas": [
        {
            "pregunta": "La función trim() modifica el objeto sobre el cual se invoca.",
            "respuesta_correcta": false,
            "respuesta_usuario":false
        },
        {
            "pregunta": "La función trim() modifica el objeto sobre el cual se invoca.",
            "respuesta_correcta": false,
            "respuesta_usuario":false
        },
        {
            "pregunta": "Node JS es un buen lenguaje.",
            "respuesta_correcta": true,
            "respuesta_usuario":true
        },
        {
            "pregunta": "Node JS es un buen lenguaje.",
            "respuesta_correcta": true,
            "respuesta_usuario":true
        }
    ]
}, {
    "track": 4,
    "tag_id": "alejandr3",
    "preguntas": [
        {
            "pregunta": "La función trim() modifica el objeto sobre el cual se invoca.",
            "respuesta_correcta": false,
            "respuesta_usuario":true
        },
        {
            "pregunta": "La función trim() modifica el objeto sobre el cual se invoca.",
            "respuesta_correcta": false,
            "respuesta_usuario":true
        },
        {
            "pregunta": "Node JS es un buen lenguaje.",
            "respuesta_correcta": true,
            "respuesta_usuario":true
        },
        {
            "pregunta": "Node JS es un buen lenguaje.",
            "respuesta_correcta": true,
            "respuesta_usuario":true
        }
    ]
}]

###
GET http://localhost:3000/config-entrance HTTP/1.1
###
GET http://localhost:3000/config-registro-en-sitio HTTP/1.1
###
GET http://localhost:3000/config-tags HTTP/1.1

###
PUT http://localhost:3300/user/6228f45183bc1976eecdcd8b HTTP/1.1
Content-Type: application/json

{
    "first_name": "Steph"
}

###
PUT http://localhost:3000/tag_id-user/624b29fbf6af77f1c08b0d74 HTTP/1.1
Content-Type: application/json

{
    "tag_id": "12345678"
}

###
GET http://localhost:3000/insert-exhibitors HTTP/1.1
###
GET http://localhost:3000/insert-stores HTTP/1.1
###
GET http://localhost:3000/insert-users HTTP/1.1

###
GET http://localhost:3000/how-many-got-in HTTP/1.1

###
GET http://localhost:3000/total-users HTTP/1.1

###
GET http://localhost:3000/top-admonitions HTTP/1.1
###
GET http://localhost:3000/admonition-by-tag?tag_id=alejandr HTTP/1.1
###
GET http://localhost:3300/influx HTTP/1.1
###
GET http://localhost:3000/insert-data-bubble HTTP/1.1
###
GET http://localhost:3000/distinct-value/badge HTTP/1.1

###
GET http://localhost:3300/sidenav?distinct=badge HTTP/1.1
###
GET http://localhost:3300/influx-time?start=2022-10-28T05:00:00.000Z&end=2022-10-29T04:59:59.999Z HTTP/1.1
###
GET http://localhost:3300/attendees?skip=0&limit=50&searchComposite=  HTTP/1.1
###
GET http://localhost:3300/status-count  HTTP/1.1
###
GET http://localhost:3300/attendee-by-status?countTagId=0&limit=50&skip=0  HTTP/1.1

### 
GET http://localhost:3300/another-endpoint?countTagId=1&countTagId=2&countTagId=0&limit=50&skip=0  HTTP/1.1

###
GET http://localhost:3300/tag_id-user?tag_id=alejandro HTTP/1.1

###
GET http://localhost:3300/attendees-table?searchComposite=alejandro

###
GET http://localhost:3300/delivered-graphic

###
GET http://localhost:3300/delivered-status?delivered=yes&skip=0&limit=20
###
GET http://localhost:3300/delivered-count
###
GET http://localhost:3300/