###
POST http://localhost:3000/new-user HTTP/1.1
content-type: application/json

{
    "registered_by_user_id": 1,
    "email": "jesusarellano334@gmail.com",
    "first_name": "Jespus",
    "identification_img_url": "google.com",
    "identification_img_file_name": "google.com",
    "last_name": "area",
    "mobile_number": "4521590132",
    "badge": "Bach",
    "adminuser": "AdminUser",
    "adminpassword": "Bach",
    "adminsub": "Bach",
    "arrivaldate": "Bach",
    "accessdate": "Bach",
    "limitdate": "Bach",
    "user_role": {
        "role": "role"
    },
    "organization_role": {  
        "region": "Bach",
        "zona": "Bach",
        "distrito": "Bach",
        "tienda": "Bach",
        "area": "Bach",
        "role": "Bach"
    }
}

###
GET http://localhost:3000/tienda?tienda=alejandro

###
GET http://localhost:3000/region?region=1005&users=jesus

###
GET http://localhost:3000/user/613fde279b17de34104caeac


###
POST http://localhost:3000/new-store HTTP/1.1
content-type: application/json

{
    "region": "Mexico",
    "zona": "La Magdalena",
    "distrito": "Federal",
    "tienda": "Merza"
}

###
GET http://localhost:3000/stores HTTP/1.1

###
GET http://localhost:3000/stores?region=Mexico&zona=La%20Magdalena HTTP/1.1


###
GET http://localhost:3000/stores/?region=Mexico&zona=La%20Magdalena&distrito=Federal HTTP/1.1 

###
POST http://localhost:3000/tag_id-user HTTP/1.1
Content-Type: application/json

{
    "tag_id": "3946b549",
    "id": "63090c20762e25fbb8fd7a36"
}

###
GET http://localhost:3000/tag_id-user?tag_id=_deconoc HTTP/1.1

###
POST http://localhost:3000/new-entrance HTTP/1.1
Content-Type: application/json

{
    "tag_id": "DHle7G{dh&72h^Jyu(j~^2vivK",
    "id_lectora": "inpulse/dt/pulses/Pulso404/tag-id",
    "event_type": "entrada"
}

###
POST http://localhost:3000/new-entrance HTTP/1.1
Content-Type: application/json

{
    "tag_id": "gafete15",
    "id_lectora": "1",
    "event_type": "entrada"
}

###
GET http://localhost:3000/questionnaries HTTP/1.1

###
GET http://localhost:3000/questionnaries?track=4 HTTP/1.1

###
POST http://localhost:3000/questionnarie HTTP/1.1
Content-Type: application/json

{
    "track": 1,
    "preguntas": [
        {
            "pregunta": "La función trim() modifica el objeto sobre el cual se invoca.",
            "respuesta_correcta": false
        },
        {
            "pregunta": "La función trim() modifica el objeto sobre el cual se invoca.",
            "respuesta_correcta": false
        },
        {
            "pregunta": "Node JS es un buen lenguaje.",
            "respuesta_correcta": true
        },
        {
            "pregunta": "Node JS es un buen lenguaje.",
            "respuesta_correcta": true
        }
    ]
}

###
POST http://localhost:3000/admonitions HTTP/1.1
Content-Type: application/json

[
    {
        "tag_id": "alejandr",
        "points": {{$randomInt 5 50}},
        "id_lectora": "31234"
    },    {
        "tag_id": "alejandre",
        "points": {{$randomInt 5 50}},
        "id_lectora": "1244"
    },    {
        "tag_id": "alejandr1",
        "points": {{$randomInt 5 50}},
        "id_lectora": "3123421"
    }
]

###
POST http://localhost:3000/answers HTTP/1.1
Content-Type: application/json

[{
    "track": 4,
    "tag_id": "alejandr1",
    "preguntas": [
        {
            "pregunta": "La función trim() modifica el objeto sobre el cual se invoca.",
            "respuesta_correcta": false,
            "respuesta_usuario":false
        },
        {
            "pregunta": "La función trim() modifica el objeto sobre el cual se invoca.",
            "respuesta_correcta": false,
            "respuesta_usuario":false
        },
        {
            "pregunta": "Node JS es un buen lenguaje.",
            "respuesta_correcta": true,
            "respuesta_usuario":true
        },
        {
            "pregunta": "Node JS es un buen lenguaje.",
            "respuesta_correcta": true,
            "respuesta_usuario":true
        }
    ]
}, {
    "track": 4,
    "tag_id": "alejandr3",
    "preguntas": [
        {
            "pregunta": "La función trim() modifica el objeto sobre el cual se invoca.",
            "respuesta_correcta": false,
            "respuesta_usuario":true
        },
        {
            "pregunta": "La función trim() modifica el objeto sobre el cual se invoca.",
            "respuesta_correcta": false,
            "respuesta_usuario":true
        },
        {
            "pregunta": "Node JS es un buen lenguaje.",
            "respuesta_correcta": true,
            "respuesta_usuario":true
        },
        {
            "pregunta": "Node JS es un buen lenguaje.",
            "respuesta_correcta": true,
            "respuesta_usuario":true
        }
    ]
}]

###
GET http://localhost:3000/config-entrance HTTP/1.1
###
GET http://localhost:3000/config-registro-en-sitio HTTP/1.1
###
GET http://localhost:3000/config-tags HTTP/1.1

###
PUT http://localhost:3000/user/6228f45183bc1976eecdcd8b HTTP/1.1
Content-Type: application/json

{
    "first_name": "Steph"
}

###
PUT http://localhost:3000/tag_id-user/624b29fbf6af77f1c08b0d74 HTTP/1.1
Content-Type: application/json

{
    "tag_id": "12345678"
}

###
GET http://localhost:3000/insert-exhibitors HTTP/1.1
###
GET http://localhost:3000/insert-stores HTTP/1.1
###
GET http://localhost:3000/insert-users HTTP/1.1

###
GET http://localhost:3000/how-many-got-in HTTP/1.1

###
GET http://localhost:3000/total-users HTTP/1.1

###
GET http://localhost:3000/top-admonitions HTTP/1.1
###
GET http://localhost:3000/admonition-by-tag?tag_id=alejandr HTTP/1.1
###
GET http://localhost:3000/influx HTTP/1.1
###
GET http://localhost:3000/insert-data-bubble HTTP/1.1
